repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: uv run ruff check
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff format
        entry: uv run ruff format --check
        language: system
        types: [python]
      - id: djhtml
        name: djhtml
        entry: uv run djhtml --check
        language: system
        types: [html]