version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - staticfiles:/app/static
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: kmicms_web
    command: /start
    volumes:
      - staticfiles:/app/static
    env_file:
      - .env
    environment:
      - SQL_DATABASE=ferry
      - SQL_USER=ferry
      - SQL_PASSWORD=ferry
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ferry
      - POSTGRES_USER=ferry
      - POSTGRES_PASSWORD=ferry

volumes:
  postgres_data:
  staticfiles: