# Generated by Django 5.1 on 2024-09-14 15:08

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0005_move_person_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("emoji", models.CharField(max_length=1)),
                ("map_url", models.URLField()),
                ("menu_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PubTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tables",
                        to="pub.pub",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PubEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp of Event")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendees",
                    models.ManyToManyField(related_name="events_attended", to="accounts.person"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.person",
                    ),
                ),
                (
                    "pub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="pub.pub",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="pub.pubtable",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="pubtable",
            constraint=models.UniqueConstraint(
                models.F("pub"),
                models.F("number"),
                name="unique_table_number_within_pub",
                violation_error_message="Another table has that number at that pub",
            ),
        ),
        migrations.AddConstraint(
            model_name="pubevent",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("timestamp"),
                models.F("pub"),
                name="unique_date_per_pub",
                violation_error_message="There is another event at that pub on that date.",
            ),
        ),
    ]
