# Generated by Django 5.1 on 2024-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pubevent",
            name="discord_id",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="Discord Scheduled Event ID",
            ),
        ),
    ]
