# Generated by Django 5.1 on 2024-11-10 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_add_autopub_toggle"),
        ("pub", "0005_add_rsvp_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pubevent",
            options={"ordering": ("-timestamp",)},
        ),
    ]
