# Generated by Django 5.1 on 2024-11-10 19:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_add_autopub_toggle"),
        ("pub", "0006_pub_event_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="PubEventBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_size",
                    models.PositiveSmallIntegerField(verbose_name="Table size"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.person",
                    ),
                ),
                (
                    "pub_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="pub.pubevent",
                    ),
                ),
            ],
        ),
    ]
