# Generated by Django 5.1 on 2024-12-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_add_autopub_toggle"),
        ("pub", "0007_add_pub_booking_model"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pubeventrsvp",
            name="correct_value_for_method",
        ),
        migrations.AlterField(
            model_name="pubeventrsvp",
            name="method",
            field=models.CharField(
                choices=[
                    ("A", "AutoPub"),
                    ("D", "Discord"),
                    ("M", "Manual Entry"),
                    ("W", "Web"),
                ],
                max_length=1,
            ),
        ),
        migrations.AddConstraint(
            model_name="pubeventrsvp",
            constraint=models.CheckConstraint(
                condition=models.Q(  # type: ignore[call-arg]
                    models.Q(("is_attending", True), ("method", "A")),
                    models.Q(("is_attending", True), ("method", "D")),
                    models.Q(("is_attending", True), ("method", "M")),
                    ("method", "W"),
                    _connector="OR",
                ),
                name="correct_value_for_method",
                violation_error_message="Invalid attendance value for RSVP method",
            ),
        ),
    ]
