# Generated by Django 5.2 on 2026-01-27 18:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_add_autopub_toggle"),
        ("pub", "0009_add_extra_info_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PubEventAttendanceTombstone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="pubeventrsvp",
            name="correct_value_for_method",
        ),
        migrations.AlterField(
            model_name="pubeventrsvp",
            name="method",
            field=models.CharField(
                choices=[
                    ("A", "AutoPub"),
                    ("D", "Discord"),
                    ("M", "Manual Entry"),
                    ("W", "Web"),
                    ("T", "Tombstone"),
                ],
                max_length=1,
            ),
        ),
        migrations.AddConstraint(
            model_name="pubeventrsvp",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_attending", True), ("method", "A")),
                    models.Q(("is_attending", True), ("method", "D")),
                    models.Q(("is_attending", True), ("method", "M")),
                    ("method", "W"),
                    models.Q(("is_attending", False), ("method", "T")),
                    _connector="OR",
                ),
                name="correct_value_for_method",
                violation_error_message="Invalid attendance value for RSVP method",
            ),
        ),
        migrations.AddField(
            model_name="pubeventattendancetombstone",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_tombstones",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="pubeventattendancetombstone",
            name="pub_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_tombstones",
                to="pub.pubevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="pubeventattendancetombstone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pub_event__isnull", True)),
                fields=("person",),
                name="one_attendance_tombstone_per_person_for_next_pub",
            ),
        ),
        migrations.AddConstraint(
            model_name="pubeventattendancetombstone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pub_event__isnull", False)),
                fields=("person", "pub_event"),
                name="one_attendance_tombstone_per_person_per_event",
                violation_error_message="There is already an attendance tombstone for this person at this event",
            ),
        ),
    ]
