# Generated by Django 4.2.9 on 2024-02-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("court", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accusation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="consequence",
            options={"ordering": ["content"]},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["display_name"], "verbose_name_plural": "people"},
        ),
        migrations.AddConstraint(
            model_name="accusation",
            constraint=models.CheckConstraint(
                check=models.Q(("suspect", models.F("created_by")), _negated=True),
                name="court_accusation_prevent_self_accusation",
            ),
        ),
    ]
