# Generated by Django 4.2.9 on 2024-02-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("court", "0002_add_api_token_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="discord_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name="Discord ID"),
        ),
        migrations.AlterField(
            model_name="person",
            name="display_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
