# Generated by Django 5.1 on 2024-09-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("court", "0004_move_person_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consequence",
            name="content",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="ratification",
            name="consequence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ratifications",
                to="court.consequence",
            ),
        ),
    ]
