# Generated by Django 5.1 on 2024-09-13 17:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_enable_linking_user_to_person"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Person",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("display_name", models.CharField(max_length=255, unique=True)),
                        (
                            "discord_id",
                            models.BigIntegerField(blank=True, null=True, unique=True, verbose_name="Discord ID"),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name_plural": "people",
                        "ordering": ["display_name"],
                    },
                ),
                migrations.AlterField(
                    model_name="user",
                    name="person",
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.person",
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
