# Generated by Django 5.1 on 2024-10-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_move_person_table"),
        ("court", "0004_move_person_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="name",
            field=models.CharField(default="API Token", max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="apitoken",
            constraint=models.UniqueConstraint(
                fields=("user", "name"),
                name="unique_name_for_token_per_user",
                violation_error_message="Please choose a unique name for the token.",
            ),
        ),
    ]
