# Generated by Django 5.1 on 2024-10-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_name_to_api_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="autopub",
            field=models.BooleanField(default=False, verbose_name="AutoPub enabled"),
        ),
    ]
